obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.09, -0.07], [-0.09, 0.07], [0.09, 0.07], [0.09, -0.07]]


# Layer definitions
static_map:
  map_topic: map
  subscribe_to_updates: true

obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: { sensor_frame: hokuyo_link, data_type: LaserScan, topic: rrbot/laser/scan, marking: true, clearing: true }

inflation_layer:
  inflation_radius: 0.05