global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  rolling_window: false

  plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer,  type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}