local_costmap:
  global_frame: map
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.1
  
  plugins: 
    - {name: obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}